### ISSUE TITLE
iMessage messages aren't processed

### ISSUE THREAD

**Issue by ankurcha** [toffer/iphone-sms-backup#1]
In case the database has any iMessage messages, they are skipped

Steps to reproduce:
1. Send an iMessage from the iphone
2. Backup the phone to the computer
3. execute ./sms-backup.py

Actual Result:

```
INFO:root:Skipping msg (13925) not sent. Address: None. Text: Doesn't play :(.
```

Expected Result: 

```
2011-12-23 22:48:20 |          FROM_NAME | (999) 999-9999 |  Doesn't play :(.
```

**Comment by arkravitz** [comment]
Could you send me that line in your database file?

**Comment by ankurcha** [comment]
I couldn't find the exact line so i got another message line

`<?xml version="1.0" encoding="UTF-8"?>
<table>
    <message>
        <ROWID>11630</ROWID>
        <address>NULL</address>
        <date>346224256</date>
        <text>I might play some n64</text>
        <flags>0</flags>
        <replace>0</replace>
        <svc_center>NULL</svc_center>
        <group_id>0</group_id>
        <association_id>0</association_id>
        <height>0</height>
        <UIFlags>0</UIFlags>
        <version>0</version>
        <subject>NULL</subject>
        <country>NULL</country>
        <headers>NULL</headers>
        <recipients>NULL</recipients>
        <read>0</read>
        <madrid_attributedBody>(null)</madrid_attributedBody>
        <madrid_handle>+14252202489</madrid_handle>
        <madrid_version>0</madrid_version>
        <madrid_guid>87CFB429-AA74-4DB7-B14A-1FFD6746A24D</madrid_guid>
        <madrid_type>0</madrid_type>
        <madrid_roomname>NULL</madrid_roomname>
        <madrid_service>Madrid</madrid_service>
        <madrid_account>p:+12139095359</madrid_account>
        <madrid_flags>12289</madrid_flags>
        <madrid_attachmentInfo>NULL</madrid_attachmentInfo>
        <madrid_url>NULL</madrid_url>
        <madrid_error>0</madrid_error>
        <is_madrid>1</is_madrid>
        <madrid_date_read>346224291</madrid_date_read>
        <madrid_date_delivered>0</madrid_date_delivered>
        <madrid_account_guid>53BAB8AE-32C3-41A0-AD57-279BCDDAD3A3</madrid_account_guid>
    </message>
</table>`

**Comment by toffer** [comment]
Thanks for pointing out this problem.  I agree that the script should include iMessage messages in the output.

The reason it skips over them right now is that iMessage messages don't fill in the `address` field in the `message` table.  Without a valid address, I figured a text wasn't worth including in the export.  Plus, it doesn't set the `flags` field to show if message is sent or received.  Instead, iMessage messages utilize the madrid_flags field for that info.

(OK, the real reason the backup script doesn't already include them is that I developed it when I was still using iOS4, so iMessage messages didn't even exist in my SMS database!)

I can see now that when Apple added the iMessage feature, they added a whole bunch of `madrid` fields to the `message` table to enable it.  (You can see all the `madrid` fields in ankurcha's message above.)

Furthermore, a unique `group_id` is no longer assigned to each address (phone number), which is inconvenient, since I was selecting by `group_id` to get all messages to/from specific phone numbers.  Instead, it looks like all iMessage messages get assigned a `group_id` of 0.

Anyway, I'll start working on including the iMessage messages, but I'm going to have to make changes both to the command line options, and to how I query the DB to do so.

I'll keep you posted on my progress.
